# Generated by Django 5.2.9 on 2025-12-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheTechnique',
            fields=[
                ('recette_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.recette', verbose_name='Recette Associée')),
                ('nombre_portions', models.IntegerField(default=1, verbose_name='Nombre de portions standard')),
                ('cout_matiere_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Coût Matière HT (€)')),
                ('marge_appliquee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Marge Commerciale (%)')),
                ('validation_admin', models.BooleanField(default=False, verbose_name='Validée par un Expert (Statut Académique)')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('materiel_requis_json', models.JSONField(default=list, verbose_name="Matériel requis (IDs de l'app 'core')")),
            ],
            options={
                'verbose_name': 'Fiche Technique Normalisée',
                'verbose_name_plural': 'Fiches Techniques Académiques',
            },
        ),
    ]
