# Generated by Django 5.2.9 on 2025-12-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0003_alter_quantiteingredient_ingredient_and_more'),
        ('techsheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichetechnique',
            options={'verbose_name': 'Fiche Technique', 'verbose_name_plural': 'Fiches Techniques'},
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='marge_appliquee',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='Marge Commerciale (%)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='materiel_requis_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Matériel requis (IDs)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='recette_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fiche_technique', serialize=False, to='recipes.recette', verbose_name='Recette Associée'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='validation_admin',
            field=models.BooleanField(default=False, verbose_name='Validée par un Expert'),
        ),
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Moyen HT (€)')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('l', 'Litre'), ('unit', 'Pièce/Unité')], default='kg', max_length=10, verbose_name="Unité d'achat")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière MAJ')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='ingredients.ingredient', verbose_name='Ingrédient')),
            ],
            options={
                'verbose_name': 'Prix Ingrédient (Mercuriale)',
                'verbose_name_plural': 'Mercuriale des Prix',
                'ordering': ['ingredient__name'],
            },
        ),
    ]
