# Generated by Django 5.2.9 on 2026-01-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsheets', '0002_alter_fichetechnique_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Terme / Technique')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('domaine', models.CharField(choices=[('Cuisine', 'Cuisine'), ('Pâtisserie', 'Pâtisserie'), ('Boulangerie', 'Boulangerie'), ('Autre', 'Autre')], default='Cuisine', max_length=50)),
                ('definition', models.TextField(verbose_name='Définition')),
                ('objectif', models.JSONField(blank=True, default=list, verbose_name='Objectifs')),
                ('principe', models.TextField(blank=True, verbose_name='Principe scientifique/technique')),
                ('exemples', models.JSONField(blank=True, default=dict, verbose_name="Exemples d'application")),
                ('erreurs_frequentes', models.JSONField(blank=True, default=list, verbose_name='Erreurs fréquentes')),
                ('niveau', models.JSONField(blank=True, default=list, verbose_name='Niveaux (CAP, Bac Pro...)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='techniques/', verbose_name='Illustration')),
            ],
            options={
                'verbose_name': 'Technique Culinaire',
                'verbose_name_plural': 'Dictionnaire Technique',
                'ordering': ['nom'],
            },
        ),
    ]
