# Generated by Django 5.2.9 on 2026-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsheets', '0003_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='categorie_cap',
            field=models.CharField(choices=[('BASE', 'Préparations de Base'), ('CUISSON', 'Cuissons'), ('SAUCE', 'Sauces & Fonds'), ('PATISSERIE', 'Pâtisserie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie CAP'),
        ),
        migrations.AddField(
            model_name='technique',
            name='is_active_techsheet',
            field=models.BooleanField(default=False, verbose_name='Fiche Technique Active'),
        ),
        migrations.AddField(
            model_name='technique',
            name='materiel',
            field=models.JSONField(blank=True, default=list, verbose_name='Matériel requis'),
        ),
        migrations.AddField(
            model_name='technique',
            name='phases',
            field=models.JSONField(blank=True, default=list, verbose_name='tapes / Phases (Technique)'),
        ),
        migrations.AddField(
            model_name='technique',
            name='reference_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Réf. CAP (ex: 1PB06)'),
        ),
    ]
