# Generated by Django 5.2.9 on 2025-12-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('CUISINE', 'Cuisine'), ('PATISSERIE', 'Pâtisserie'), ('BOULANGERIE', 'Boulangerie'), ('AUTRE', 'Autre')], default='CUISINE', max_length=20, verbose_name='Catégorie de cuisine')),
                ('restaurant', models.CharField(blank=True, max_length=255, verbose_name='Restaurant principal')),
                ('date_de_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_de_deces', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('pays_d_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.pays', verbose_name="Pays d'origine")),
            ],
            options={
                'verbose_name': 'Chef Célèbre',
                'verbose_name_plural': 'Chefs Célèbres',
            },
        ),
    ]
