# Generated by Django 5.2.9 on 2025-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glossaire',
        ),
        migrations.DeleteModel(
            name='Materiel',
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
