# Generated by Django 5.2.9 on 2025-12-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=150, unique=True, verbose_name='Terme technique')),
                ('definition', models.TextField(verbose_name='Définition académique')),
                ('type_terme', models.CharField(choices=[('V', "Verbe d'Action"), ('N', 'Nom de Produit/Ustensile'), ('A', "Adjectif/Terme d'État")], default='N', max_length=1, verbose_name='Type de terme')),
            ],
            options={
                'verbose_name': 'Terme de Glossaire',
                'verbose_name_plural': 'Glossaire Terminologique',
                'ordering': ['terme'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'équipement")),
                ('description_courte', models.TextField(verbose_name='Fonction principale')),
                ('categorie', models.CharField(choices=[('U', 'Ustensile/Petit Matériel'), ('M', 'Machine de Cuisson/Froid'), ('P', 'Préparation Spécifique')], default='U', max_length=1, verbose_name='Catégorie')),
                ('maintenance_checklist', models.JSONField(blank=True, null=True, verbose_name="Checklist d'entretien")),
            ],
            options={
                'verbose_name': 'Matériel/Équipement',
                'verbose_name_plural': 'Catalogue Matériel',
                'ordering': ['nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=100, unique=True, verbose_name='Nom du Pays (français)')),
                ('continent', models.CharField(max_length=50, verbose_name='Continent')),
                ('plats_phares_json', models.JSONField(blank=True, null=True, verbose_name='Plats emblématiques (JSON)')),
            ],
            options={
                'verbose_name': 'Pays (Atlas)',
                'verbose_name_plural': 'Pays (Atlas)',
                'ordering': ['nom_fr'],
            },
        ),
    ]
