# Generated by Django 5.2.9 on 2025-12-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulinaryUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Usage')),
            ],
            options={
                'verbose_name': 'Usage Culinaire',
                'verbose_name_plural': 'Usages Culinaires',
            },
        ),
        migrations.CreateModel(
            name='FunctionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catégorie Fonctionnelle',
                'verbose_name_plural': 'Catégories Fonctionnelles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (classe CSS/SVG)')),
            ],
            options={
                'verbose_name': 'Catégorie Principale',
                'verbose_name_plural': 'Catégories Principales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Famille d'ingrédient",
                'verbose_name_plural': "Familles d'ingrédients",
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='labels/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Label / Certification',
                'verbose_name_plural': 'Labels / Certifications',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom principal')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='Nom scientifique')),
                ('description', models.TextField(verbose_name='Description générale')),
                ('seasonality', models.CharField(blank=True, max_length=100, verbose_name='Saisonnalité')),
                ('flavor_profile', models.TextField(blank=True, verbose_name='Profil aromatique/Saveur')),
                ('texture', models.TextField(blank=True, verbose_name='Texture')),
                ('buying_guide', models.TextField(blank=True, verbose_name="Guide d'achat")),
                ('storage_guide', models.TextField(blank=True, verbose_name='Guide de conservation')),
                ('prep_guide', models.TextField(blank=True, verbose_name='Conseils de préparation')),
                ('nutrition_info', models.TextField(blank=True, verbose_name='Infos nutritionnelles')),
                ('allergens', models.TextField(blank=True, verbose_name='Allergènes')),
                ('specific_data', models.JSONField(blank=True, default=dict, verbose_name='Données spécifiques (JSON)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='ingredients/main/', verbose_name='Image principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('culinary_uses', models.ManyToManyField(blank=True, to='ingredients.culinaryuse', verbose_name='Usages recommandés')),
                ('functional_categories', models.ManyToManyField(blank=True, related_name='ingredients', to='ingredients.functionalcategory', verbose_name='Catégories Fonctionnelles')),
                ('origins_countries', models.ManyToManyField(blank=True, related_name='ingredients_originaires', to='atlas.pays', verbose_name="Pays d'origine majeurs")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='ingredients.ingredientcategory', verbose_name='Catégorie Principale')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingredientfamily', verbose_name='Famille')),
                ('labels', models.ManyToManyField(blank=True, to='ingredients.label', verbose_name='Labels compatibles')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ingredients/variations/')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Légende (ex: Moulu, Entier)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ingredients.ingredient')),
            ],
            options={
                'verbose_name': 'Image additionnelle',
                'verbose_name_plural': 'Galerie Images',
                'ordering': ['order'],
            },
        ),
    ]
