# Generated by Django 5.2.9 on 2025-12-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='glossary_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_lies', to='atlas.glossaire', verbose_name='Terme du Glossaire (Atlas)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier image (Référence)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags n8n/IA'),
        ),
    ]
