# Generated by Django 5.2.9 on 2026-01-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_glossary_term_ingredient_image_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / Introduction'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Photo de couverture'),
        ),
    ]
