# Generated by Django 5.2.9 on 2025-12-15 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='auteurs',
            field=models.ManyToManyField(related_name='recettes_contribuees', to=settings.AUTH_USER_MODEL, verbose_name='Auteurs / Contributeurs'),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(related_name='recettes_contenues', through='recipes.QuantiteIngredient', to='recipes.ingredient', verbose_name='Ingrédients de la recette'),
        ),
        migrations.AddField(
            model_name='quantiteingredient',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recette'),
        ),
        migrations.AddField(
            model_name='recette',
            name='techniques_cles',
            field=models.ManyToManyField(related_name='recettes_utilisant_technique', to='recipes.technique', verbose_name='Techniques clés'),
        ),
        migrations.AlterUniqueTogether(
            name='quantiteingredient',
            unique_together={('recette', 'ingredient')},
        ),
    ]
