# Generated by Django 5.2.9 on 2025-12-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantiteingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingredients.ingredient', verbose_name='Ingrédient Brut'),
        ),
        migrations.AlterModelOptions(
            name='quantiteingredient',
            options={'ordering': ['id'], 'verbose_name': "Ligne d'ingrédient", 'verbose_name_plural': "Lignes d'ingrédients"},
        ),
        migrations.AlterUniqueTogether(
            name='quantiteingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quantiteingredient',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note (ex: coupé en dés)'),
        ),
        migrations.AddField(
            model_name='quantiteingredient',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisations_comme_ingredient', to='recipes.recette', verbose_name='Sous-Recette (ex: Sauce, Pâte)'),
        ),
        migrations.AddField(
            model_name='recette',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='sub_recipes',
            field=models.ManyToManyField(related_name='super_recipes', through='recipes.QuantiteIngredient', through_fields=('recette', 'sub_recipe'), to='recipes.recette', verbose_name='Sous-recettes requises'),
        ),
        migrations.AlterField(
            model_name='quantiteingredient',
            name='quantite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quantiteingredient',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_ingredients', to='recipes.recette'),
        ),
        migrations.AlterField(
            model_name='quantiteingredient',
            name='unite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(related_name='recettes_utilisees', through='recipes.QuantiteIngredient', through_fields=('recette', 'ingredient'), to='ingredients.ingredient', verbose_name='Ingrédients requis'),
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='recipes.recipecategory', verbose_name='Catégorie Parente')),
            ],
            options={
                'verbose_name': 'Catégorie de Recette',
                'verbose_name_plural': 'Catégories de Recettes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recette',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes', to='recipes.recipecategory', verbose_name='Catégorie'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
