# Generated by Django 5.2.9 on 2025-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_quantiteingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Instructions de préparation'),
        ),
        migrations.AddField(
            model_name='recette',
            name='notes_chef',
            field=models.TextField(blank=True, verbose_name='Notes du Chef / Astuces'),
        ),
    ]
